version: "3"

services:
  frontend:
    build: ./react-app
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - backend

  backend:
    build: ./nest-api
    ports:
      - 3000:3000
    volumes:
      - ./nest-api:/home/node/app